#!/usr/bin/env bash
# Print usage
usage() {
    cat << EOF

NAME
    etl - Run the NLM-CKN ETL pipeline

SYNOPSIS
    etl [OPTIONS]

DESCRIPTION
    Run the NLM-CKN ETL pipeline by making a clean package, downloading
    ontologies, building the ontology graph, building the results and
    phenotype graphs, and archiving the outputs. Must be run from the
    src/main/shell directory.

    Two archives are produced in the repo root:
      obo.tar.gz      - Downloaded OWL files and files generated by
                        OntologyGraphBuilder (data/obo/), fetched
                        external API data (data/external/), and
                        result tuples written by Python
                        (data/tuples/)
      arangodb.tar.gz - ArangoDB data directory (ARANGO_DB_HOME)

OPTIONS
    -o    Build the ontology graph, if it has not been built

    -O    Force -o

    -r    Build the results and phenotype graphs, if they have not
          been built

    -R    Force -r

    -a    Make the archives, if they have not been made

    -A    Force -a

    -h    Help

    -e    Exit immediately if a command returns a non-zero status

    -x    Print a trace of simple commands

EOF
}

# Parse command line options
run_ontology=0
force_ontology=0
run_results=0
force_results=0
make_archive=0
force_archive=0
while getopts ":oOrRaAhex" opt; do
    case $opt in
        o)
            run_ontology=1
            ;;
        O)
            force_ontology=1
            ;;
        r)
            run_results=1
            ;;
        R)
            force_results=1
            ;;
        a)
            make_archive=1
            ;;
        A)
            force_archive=1
            ;;
        h)
            usage
            exit 0
            ;;
        e)
            set -e
            ;;
        x)
            set -x
            ;;
        \?)
            echo "Invalid option: -${OPTARG}" >&2
            usage
            exit 1
            ;;
        \:)
            echo "Option -${OPTARG} requires an argument" >&2
            usage
            exit 1
            ;;
    esac
done

# Parse command line arguments
shift `expr ${OPTIND} - 1`
if [[ "$#" -ne 0 ]]; then
    echo "No arguments required"
    exit 1
fi

# Require at least one action flag
if [[ $run_ontology -eq 0 && $force_ontology -eq 0 \
   && $run_results -eq 0 && $force_results -eq 0 \
   && $make_archive -eq 0 && $force_archive -eq 0 ]]; then
    usage
    exit 0
fi

# Assign the repo root and classpath
pushd "../../.." > /dev/null
classpath="target/nlm-ckn-etl-1.0.jar"
java_opts="-Xmx4g"

# Load NCBI E-Utilities credentials (NCBI_EMAIL, NCBI_API_KEY) if present.
# Create python/src/.zshenv with those two exports to enable external API fetching.
if [[ -f "python/src/.zshenv" ]]; then
    source "python/src/.zshenv"
fi

# Assign ArangoDB connection defaults
export ARANGO_DB_PORT=8529
export ARANGO_DB_HOME="$(pwd)/data/arangodb"

# Generate a random password on first run and persist it so subsequent
# runs (e.g. -R alone) can reconnect to an existing ArangoDB instance
if [[ -f ".arangodb-password" ]]; then
    export ARANGO_DB_PASSWORD=$(cat .arangodb-password)
else
    export ARANGO_DB_PASSWORD=$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32)
    echo "$ARANGO_DB_PASSWORD" > .arangodb-password
fi

# Build the ontology graph, if specified
if [[ $run_ontology -eq 1 ]] && [[ -f ".built-ontology" ]] \
       && [[ $force_ontology -eq 0 ]]; then
    echo "Ontology graph already built; use -O to force rebuild"
    echo "  $(cat .built-ontology)"
elif [[ ! -f ".built-ontology" ]] && [[ $run_ontology -eq 1 ]] \
       || [[ $force_ontology -eq 1 ]]; then

    echo "Building ontology graph"

    # Stop ArangoDB and remove the database
    pushd "src/main/shell" > /dev/null
    ./stop-arangodb.sh
    popd > /dev/null
    rm -rf "$ARANGO_DB_HOME"
    pushd "src/main/shell" > /dev/null
    ./start-arangodb.sh
    popd > /dev/null

    # Get the ArangoDB container ID for network sharing
    arangodb_id=$(docker ps | grep arangodb | cut -d " " -f 1)
    if [[ -z "$arangodb_id" ]]; then
        echo "ArangoDB container is not running"
        exit 1
    fi

    # Make a clean package
    docker run --rm \
        -v "$(pwd)":/app \
        -v "$HOME/.m2":/root/.m2 \
        -w /app \
        maven:3-eclipse-temurin-21 \
        mvn clean package -DskipTests \
    || { echo "Maven build failed"; exit 1; }

    # Validate the JAR was produced
    if [[ ! -f "$classpath" ]]; then
        echo "JAR not found at $classpath after Maven build"
        exit 1
    fi

    # Download ontologies
    docker run --rm \
        -v "$(pwd)":/app \
        -w /app \
        eclipse-temurin:21 \
        java $java_opts -cp $classpath gov.nih.nlm.OntologyDownloader \
    || { echo "OntologyDownloader failed"; exit 1; }

    # Validate OWL files were downloaded
    if ! ls data/obo/*.owl &>/dev/null; then
        echo "No OWL files found in data/obo/ after OntologyDownloader"
        exit 1
    fi

    # Build the ontology graph
    docker run --rm \
        -v "$(pwd)":/app \
        -w /app \
        --network container:$arangodb_id \
        -e ARANGO_DB_HOST=localhost \
        -e ARANGO_DB_PORT=$ARANGO_DB_PORT \
        -e ARANGO_DB_USER=root \
        -e ARANGO_DB_PASSWORD=$ARANGO_DB_PASSWORD \
        eclipse-temurin:21 \
        java $java_opts -cp $classpath gov.nih.nlm.OntologyGraphBuilder \
    || { echo "OntologyGraphBuilder failed"; exit 1; }

    # Log the build
    log_message="Built ontology graph on $(date)"
    echo $log_message > ".built-ontology"
    echo $log_message

    # Clear any existing archive so -a re-archives after a new build
    rm -f ".archived"

fi

# Build the results and phenotype graphs, if specified
if [[ $run_results -eq 1 ]] && [[ -f ".built-results" ]] \
       && [[ $force_results -eq 0 ]]; then
    echo "Results and phenotype graphs already built; use -R to force rebuild"
    echo "  $(cat .built-results)"
elif [[ ! -f ".built-results" ]] && [[ $run_results -eq 1 ]] \
       || [[ $force_results -eq 1 ]]; then

    echo "Building results and phenotype graphs"

    # Get the ArangoDB container ID for network sharing
    arangodb_id=$(docker ps | grep arangodb | cut -d " " -f 1)
    if [[ -z "$arangodb_id" ]]; then
        echo "ArangoDB container is not running"
        exit 1
    fi

    # Build the Python Docker image for linux/amd64 (scikit-misc has no
    # linux/arm64 binary wheels; amd64 wheels work via Rosetta on Apple Silicon).
    # DOCKER_BUILDKIT=1 enables --mount=type=cache in the Dockerfile so the uv
    # wheel cache persists across builds.
    DOCKER_BUILDKIT=1 docker build --platform linux/amd64 -t nlm-ckn-etl-python \
        -f src/main/shell/Dockerfile.python . \
    || { echo "Failed to build Python Docker image"; exit 1; }

    # Ensure tuples directory exists and remove any existing tuples
    mkdir -p data/tuples
    rm -f data/tuples/*.json

    # Fetch external data and write all tuples.
    # NCBI_EMAIL and NCBI_API_KEY are sourced from python/src/.zshenv above
    # and forwarded as container env vars (standard Docker pattern — no file
    # sourcing inside the container).
    docker run --rm \
        -v "$(pwd)":/app \
        --network container:$arangodb_id \
        -e ARANGO_DB_PASSWORD=$ARANGO_DB_PASSWORD \
        -e NCBI_EMAIL=${NCBI_EMAIL:-} \
        -e NCBI_API_KEY=${NCBI_API_KEY:-} \
        nlm-ckn-etl-python \
        sh -c "python /app/python/src/ExternalApiResultsFetcher.py \
            && python /app/python/src/NSForestResultsTupleWriter.py \
            && python /app/python/src/AuthorToClResultsTupleWriter.py \
            && python /app/python/src/ExternalApiResultsTupleWriter.py" \
    || { echo "Python scripts failed (check python/src/.zshenv credentials and data/results-sources-*.json input paths)"; exit 1; }

    # Validate tuple files were produced
    if ! ls data/tuples/*.json &>/dev/null; then
        echo "No JSON files in data/tuples/ after Python tuple writers ran"
        echo "  Ensure data/results-sources-*.json points to existing NSForest results"
        exit 1
    fi
    echo "  Tuple files: $(ls data/tuples/*.json | wc -l | tr -d ' ') JSON file(s) in data/tuples/"

    # Make a clean package
    docker run --rm \
        -v "$(pwd)":/app \
        -v "$HOME/.m2":/root/.m2 \
        -w /app \
        maven:3-eclipse-temurin-21 \
        mvn clean package -DskipTests \
    || { echo "Maven build failed"; exit 1; }

    # Validate the JAR was produced
    if [[ ! -f "$classpath" ]]; then
        echo "JAR not found at $classpath after Maven build"
        exit 1
    fi

    # Build the results graph
    docker run --rm \
        -v "$(pwd)":/app \
        -w /app \
        --network container:$arangodb_id \
        -e ARANGO_DB_HOST=localhost \
        -e ARANGO_DB_PORT=$ARANGO_DB_PORT \
        -e ARANGO_DB_USER=root \
        -e ARANGO_DB_PASSWORD=$ARANGO_DB_PASSWORD \
        eclipse-temurin:21 \
        java $java_opts -cp $classpath gov.nih.nlm.ResultsGraphBuilder \
    || { echo "ResultsGraphBuilder failed"; exit 1; }

    # Build the phenotype graph
    docker run --rm \
        -v "$(pwd)":/app \
        -w /app \
        --network container:$arangodb_id \
        -e ARANGO_DB_HOST=localhost \
        -e ARANGO_DB_PORT=$ARANGO_DB_PORT \
        -e ARANGO_DB_USER=root \
        -e ARANGO_DB_PASSWORD=$ARANGO_DB_PASSWORD \
        eclipse-temurin:21 \
        java $java_opts -cp $classpath gov.nih.nlm.PhenotypeGraphBuilder \
    || { echo "PhenotypeGraphBuilder failed"; exit 1; }

    # Create analyzers and views
    docker run --rm \
        -v "$(pwd)":/app \
        --network container:$arangodb_id \
        -e ARANGO_DB_PASSWORD=$ARANGO_DB_PASSWORD \
        nlm-ckn-etl-python \
        python /app/python/src/CellKnSchemaUtilities.py \
    || { echo "CellKnSchemaUtilities failed"; exit 1; }

    # Log the build
    log_message="Built results and phenotype graphs on $(date)"
    echo $log_message > ".built-results"
    echo $log_message

    # Clear any existing archive so -a re-archives after a new build
    rm -f ".archived"

fi

# Make archives, if specified
if [[ $make_archive -eq 1 ]] && [[ -f ".archived" ]] \
       && [[ $force_archive -eq 0 ]]; then
    echo "Archives already made; use -A to force re-archive"
    echo "  $(cat .archived)"
elif [[ ! -f ".archived" ]] && [[ $make_archive -eq 1 ]] \
       || [[ $force_archive -eq 1 ]]; then

    echo "Making archives"

    # Archive the OWL files, files generated by OntologyGraphBuilder,
    # fetched external API data, and result tuples written by Python.
    # Only include directories that exist (e.g. external and tuples
    # are absent if the results stage has not been run)
    obo_paths="data/obo"
    [[ -d "data/external" ]] && obo_paths="$obo_paths data/external"
    [[ -d "data/tuples" ]] && obo_paths="$obo_paths data/tuples"
    tar -czf obo.tar.gz $obo_paths

    # Archive the ArangoDB data directory
    tar -czf arangodb.tar.gz \
        -C "$(dirname $ARANGO_DB_HOME)" \
        "$(basename $ARANGO_DB_HOME)"

    # Log the archive
    log_message="Archived obo and arangodb on $(date)"
    echo $log_message > ".archived"
    echo $log_message

fi

popd > /dev/null
